### ISSUE TITLE
Setting Image.Source to local image (added as "Content" to Assets/ folder in UWP project) leads to WASM app never going past the Splashscreen

### ISSUE THREAD

**Issue by danielkornev** [nventive/Uno#1]
![image](https://user-images.githubusercontent.com/5264043/39726043-6f61a02e-5256-11e8-9edc-eaecf16fc5e0.png)

OS: Windows 10, 1709, x64
Machine: ThinkPad X1 Carbon 4th Gen, 16GB RAM, Intel Core i7 6th gen (6600), 0.5TB SSD
Visual Studio: 2017 Pro, v 15.6.7
Python 2.7.x installed

**Comment by danielkornev** [comment]
ok, seems like it was some fault on my side.

**Comment by carldebilly** [comment]
If you put the image in the UWP asset folder (in the _UWP Head_ project), it won't be available for other heads.

Is it possible for you to fork the repo and share a commit reproducing the problem? (or any other way to give us more information to reproduce it) I would love to fix the problem for you :-).

(by the way, congrats, you're the first one to report a bug on this repo!)

**Comment by danielkornev** [comment]
Hi Carl!

Thanks for reaching out.

I don’t know where I shall put the image for it to be reachable (and visible in UI) within the WASM app. If you can recommend me the step-by-step approach here it would solve the problem.

By now, the only way I can show an image is by linking to an image hosted externally on the web.

What I want is to add an image to the project, ship it with the project, and show it in the UI.

Best Regards,
Daniel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jeromelaban** [comment]
@danielkornev "local" files should be available in the wasm app if the build action is set to `Content`. It seems that for now, wasm does not support this properly, we'll fix it.

Thanks for trying uno out !

**Comment by danielkornev** [comment]
They are available, indeed, but if I set Image.Source to such local file, app never finishes loading in web browsers.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BeaumerF** [comment]
I updated my nugget packages and it doesn't work for me on wasm (uwp yes).
``Source="ms-appx:///Assets/pictures/user.png"``

**Comment by jeromelaban** [comment]
@BeaumerF The package that fixed this was not published, you can try updating again, it should work better now.

**Comment by BeaumerF** [comment]
@jeromelaban It still doesn't work on my project, the local images let the app on the splash screen (I updated, cleaned and built)

**Comment by danielkornev** [comment]
Still doesn't work. I've added an image to Assets folders in both UWP and Android projects, but image just doesn't shop up:

![image](https://user-images.githubusercontent.com/5264043/46257912-c9084380-c4ca-11e8-867d-851d55a3799d.png)

Here's what I expect to see:
![image](https://user-images.githubusercontent.com/5264043/46257920-eccb8980-c4ca-11e8-8d68-39c064c76164.png)

Here's what I get instead (button has background color just to make sure it's positioned where it is):
![screenshot_20180930-152004_zuassistant](https://user-images.githubusercontent.com/5264043/46257942-23a19f80-c4cb-11e8-90bd-086bc8c5875e.jpg)

My Android Phone is Samsung Note 8, with Android 8.0 (Oreo) on it.

Here's the layout I've built in XAML:
```
<Page
    x:Class="ZU.Assistant.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d" FontFamily="Segoe UI Black">
    
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Border Margin="0,0,0,0" HorizontalAlignment="Stretch" VerticalAlignment="Top" Height="40" Background="#FF66AEE7">
            <TextBlock Text="ZET UNIVERSE: ASSISTANT" FontSize="18" FontFamily="Segoe UI Black" Foreground="White" FontWeight="Bold" HorizontalAlignment="Left" Height="17" Padding="0" Margin="25,11,0,0" VerticalAlignment="Top" Width="325" />
        </Border>

        <Button Height="50" Width="150" Content="Hello world!" VerticalAlignment="Center" HorizontalAlignment="Center" Click="Button_Click"/>

        <Grid HorizontalAlignment="Stretch" VerticalAlignment="Bottom" Height="52">
            <Button x:Name="speakToMeButton" HorizontalAlignment="Center" VerticalAlignment="Top" Width="50" Height="50" Padding="-2" Background="Transparent" BorderThickness="0">
                <Border Padding="0" Width="50" Height="50" Background="#FF66AEE7" CornerRadius="25" BorderThickness="1" BorderBrush="White">
                    <Image Width="48" Height="48" Source="ms-appx:///Assets/Mic-WF.png"/>
                </Border>
            </Button>
        </Grid>
    </Grid>
</Page>
```
