### ISSUE TITLE
ColumnDefinitions.Clear() throws an exception

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#1006]
## Current behavior

Calling Grid.ColumnDefinitions.Clear() throws an exception.

## How to reproduce it (as minimally and precisely as possible)

```
gridDeviceInfo.ColumnDefinitions.Clear();
gridDeviceInfo.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Auto });
gridDeviceInfo.ColumnDefinitions.Clear(); //Throws System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
```

## Environment

Nuget Package:

Package Version(s): 1.45

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Should use the new [`MaterializableList`](https://github.com/nventive/Uno/blob/master/src/Uno.UWP/Collections/MaterializableList.cs) to fix this.

**Comment by jeromelaban** [comment]
Cannot use it, it's a dictionary there.

**Comment by carldebilly** [comment]
We should create a new `MaterializableDictionary` using the same patterns ;-)
