### ISSUE TITLE
Events of items of ListView are not invoked

### ISSUE THREAD

**Issue by zipswich** [nventive/Uno#1009]
## Current behavior
Clicking a button or holding a control of an item does not invoke corresponding events.

## Expected behavior

The events should be invoked.

## How to reproduce it (as minimally and precisely as possible)

Use the attached project as repro

## Environment

VS2017 Enterprise on Windows 10 1809 paired with Macbook Pro

Nuget Package:
Uno.UI

Package Version(s):
1.45.0-dev.1705
Affected platform(s):
- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

[UnoDebug.zip](https://github.com/nventive/Uno/files/3249923/UnoDebug.zip)

**Comment by jeromelaban** [comment]
Related to #1014, where button click does not work properly

**Comment by jeromelaban** [comment]
Can also be related to event registration early collection, for that generated delegate: 

https://github.com/nventive/Uno/blob/6864661e8005ea2618478b9f5bc724c44ea40e14/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L2083

It should be hard referenced in the enclosing class.

**Comment by zipswich** [comment]
Confirmed button click is working now.👍
Touch event still does not seem to work, but it does not matter anymore for my project because I have added a button to do the work.
