### ISSUE TITLE
WASM ListView Does not show Header not Footer

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#1011]
WASM ListView Does not show Header not Footer

## Current behavior

 Header and Footer are not show

## How to reproduce it (as minimally and precisely as possible)

I attached a sample project
[WasmHeader.zip](https://github.com/nventive/Uno/files/3253690/WasmHeader.zip)

## Environment

Nuget Package:

Package Version(s):
"Uno.UI" Version="1.45.0-dev.1707" 
"Uno.Wasm.Bootstrap" Version="1.0.0-dev.281"
Affected platform(s):
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
This falls under https://github.com/nventive/Uno/issues/234

**Comment by ghuntley** [comment]
Closing this off as a duplicate. Keep an eye on #234 or if you want it faster, please send in a pull-request that implements it.
