### ISSUE TITLE
Android AutoSuggestBox Suggestion Stops Working

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#1012]
Android AutoSuggestBox Suggestion Stops Working

## Current behavior

 private void AutoSuggestBox_TextChanged(AutoSuggestBox sender, AutoSuggestBoxTextChangedEventArgs args)
        {
            if (args.Reason == AutoSuggestionBoxTextChangeReason.UserInput)
            {
                Suggestions.Clear();
                Suggestions.Add(sender.Text + "1");
                Suggestions.Add(sender.Text + "2");
            }
            Control2.ItemsSource = Suggestions;
        }
Only in Android, this code hang  adding new suggestions, first Keypress Work, Second KeyPress hang the app
[AutoSugges.zip](https://github.com/nventive/Uno/files/3253838/AutoSugges.zip)

## Environment

Nuget Package:
"Uno.UI" Version="1.45.0-dev.1707"
"Uno.Wasm.Bootstrap" Version="1.0.0-dev.281" 
Package Version(s):

Affected platform(s):
- [ ] iOS
- [X ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X ] 2019 (version: 16.1 )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
A workaround can be to copy the following template: 

https://github.com/nventive/Uno/blob/94f551bf21793c87fff1f88173ac1ad488fd8043/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L8309

But with a non-virtualizing panel for the list view in the popup:

```
<ListView.ItemsPanel>
  <ItemsPanelTemplate>
   <StackPanel />
  </ItemsPanelTemplate>
</ListView.ItemsPanel>
```

This will prevent the app from freezing (into a recycling loop, @davidjohnoliver that may interest you), but the popup is stealing the focus, so you have to tap the textbox after the searchbox appears.
