### ISSUE TITLE
Image control in Xaml without specified Source causes Wasm error

### ISSUE THREAD

**Issue by zipswich** [nventive/Uno#105]
`<Image Name="imageIntegratedButton" Stretch="Fill" Opacity="0.7"/>`
The above code causes the following Wasm error:
Uno.UI.js:258 Error: <rect> attribute height: Expected length, "NaN".
setAttribute @ Uno.UI.js:258
(anonymous) @ VM3147:1
ASM_CONSTS @ mono.js:1
...

The following code works:
<Image Name="imageIntegratedButton" Stretch="Fill" Opacity="0.7" Source="Assets\Store Logo 50x50.png"/>

**Comment by carldebilly** [comment]
Source : <https://gitter.im/uno-platform/Lobby?at=5b48a3c91c0f906b144f4152>
Occurring when there's no _source_ on the image.

**Comment by jeromelaban** [comment]
This issue has been fixed in recent updates, thanks!
