### ISSUE TITLE
Reflection unreliable in wasm

### ISSUE THREAD

**Issue by peternary** [nventive/Uno#1072]
## Current behavior

Reflection does not reliably discover static properties on static classes in wasm.  Type.GetProperty, for instance, only seems to be able to find a property if that property is referenced explicitly somewhere in code.

## Expected behavior

Reflection should work as it does in UWP environment.

## How to reproduce it (as minimally and precisely as possible)

[WasmReflection.zip](https://github.com/nventive/Uno/files/3291469/WasmReflection.zip)

In wasm this attempts to read all properties from a static class, but returns none.  Another reflection example using another class works as expected.  Reflection in both cases works as expected when in UWP.

## Environment

Nuget Package:
Uno.UI
Package Version(s):
1.45.0-dev.1813
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is not a reliability issue, this is related to the use of a linker. You can use the [linker settings file](https://github.com/nventive/Uno.Wasm.Bootstrap#linker-configuration) to control this behavior.

**Comment by peternary** [comment]
Hey, that did the trick.
