### ISSUE TITLE
Support for Workflow Designer?

### ISSUE THREAD

**Issue by dburner** [nventive/Uno#109]
Could it be possible to add support for Workflow Designer in the WebAssembly projects?

**Comment by jeromelaban** [comment]
@dburner would you have an example of this scenario ?

**Comment by dburner** [comment]
I was asking if it would be possible to run the Workflow Designer in the browser using Uno :)

**Comment by carldebilly** [comment]
It would be nice. But the workflow designer is a WPF component. It means it should be ported to Uwp first before using it with Uno.

I'm not sure if the sources are published, allowing this port to happend.

**Comment by dburner** [comment]
Ok, thank you.
