### ISSUE TITLE
Cannot create a Pivot including header in Xaml

### ISSUE THREAD

**Issue by markinnh** [nventive/Uno#112]
I was talking with your support staff through Gitter and he felt this might be a bug, It shows the last page, but does not show the header, so you cannot change pages.  

```
<Pivot Background="PaleGoldenrod">
        <PivotItem Header="Page1"
                   Background="PaleGoldenrod">
                 <views:Page1/>
        </PivotItem>
        <PivotItem Header="Page2"
                   Background="PaleGoldenrod">
 
                <views:Page2/>
 
        </PivotItem>
    </Pivot>
```

**Comment by Dissolute** [comment]
@markinnh You need to wrap your sample in code formatting for it to display correctly.

**Comment by HaoLife** [comment]
@Dissolute Can you provide an example

**Comment by Dissolute** [comment]
@HaoLife The original post is now a good example! More info [here](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

**Comment by HaoLife** [comment]
@Dissolute I'm sorry, I said is the pivot of example.


This example can't use, can provide a sample can be used

    
    <xamarin:Style x:Key="NativeDefaultPivot" TargetType="Pivot">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="Pivot">
					<NativePivotPresenter x:Name="NativePresenter" />
				</ControlTemplate>
            </Setter.Value>
        </Setter>
    </xamarin:Style>

    
    <ios:Style TargetType="NativePivotPresenter">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="Pivot">
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="1*" />
                            <RowDefinition Height="Auto" />
                        </Grid.RowDefinitions>
                        <Grid x:Name="PART_Content" Grid.Row="0" />
                        <UITabBar Grid.Row="1" />
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </ios:Style>

	<android:Style TargetType="NativePivotPresenter">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="Pivot">
                    <ExtendedViewPager OffscreenPageLimit="1" SwipeEnabled="true" />
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </android:Style>
