### ISSUE TITLE
Please implement the Dispatcher

### ISSUE THREAD

**Issue by queequac** [nventive/Uno#116]
My existing code base has lots of references to `CoreApplication.MainView.CoreWindow.Dispatcher`, which shows up as "not implemented in UNO".

Any chance to get this implemented soon? Or is there a suitable alternative for an UI thead dispatcher that works with Uno?

**Comment by Dissolute** [comment]
CoreDispatcher is [already implemented](https://github.com/nventive/Uno/blob/master/src/Uno.UWP/UI/Core/CoreDispatcher.cs) so we can certainly add support for this property.

For now the nearest equivalent property would be Window.Current.Dispatcher.

**Comment by jeromelaban** [comment]
This is indeed an easy addition, though `CoreApplication` is a bit more complex to add. I've made a PR to add `CoreWindow.Dispatcher`, since it can be accessed from other locations, and it will make it easier to port code, but not through `CoreApplication.MainView` yet.

**Comment by queequac** [comment]
Sounds good... but unfortunately seems to be no solution for my library code.
`Window.Current` is null and CoreWindow does not have `GetForCurrentThread()` implemented yet. So I am still not sure how I should reach some suitable Dispatcher. :(

**Comment by jeromelaban** [comment]
> Window.Current is null

Is it null under Uno or under Windows ? Under Uno, `Window.Current` [always returns an instance](https://github.com/nventive/Uno/blob/808f788688b82118ad1bee0bd0cbaec5b0ad421f/src/Uno.UI/UI/Xaml/Window.cs#L37) whereas on windows, it returns a window if the current thread is a UI thread.

**Comment by queequac** [comment]
Ah, good to know, just tried it quickly under Windows.
So I will probably add a conditional or a platform-specific preprocessor directive.

Thanks!
