### ISSUE TITLE
VirtualKeyModifiers is confused

### ISSUE THREAD

**Issue by Daoting** [nventive/Uno#138]
Uwp must use Windows.System.VirtualKeyModifiers,
Others must use Windows.UI.Xaml.Input.VirtualKeyModifiers. Compilation Error.

**Comment by jeromelaban** [comment]
Indeed, this type is a duplicate:
https://github.com/nventive/Uno/blob/26c5cc5992cae3c8c25adf51eb77ca4b0dd34e93/src/Uno.UI/UI/Xaml/Input/VirtualKeyModifiers.cs
and
https://github.com/nventive/Uno/blob/26c5cc5992cae3c8c25adf51eb77ca4b0dd34e93/src/Uno.UWP/Generated/3.0.0.0/Windows.System/VirtualKeyModifiers.cs

`Windows.System.VirtualKeyModifiers` is the proper namespace.

**Comment by Daoting** [comment]
Thanks.
