### ISSUE TITLE
Android , Is  Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView() implemented?

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#142]
HI
This code fails without a runtime error on Android and IOs
var resourceLoader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView();
var a = resourceLoader.GetString(value);

It does work on UWP.

how do you implement multy language Strings??

Thanks

**Comment by Dissolute** [comment]
ResourceLoader.GetString() isn't implemented.

On Android+iOS, the ResourceHelper class supplies this functionality, but requires a bit of manual setup:

Add the following to `Application.OnLaunched` (in App.xaml.cs):
``` csharp
#if __ANDROID__
			ResourceHelper.ResourcesService = new Uno.UI.Services.ResourcesService(Uno.UI.ContextHelper.Current);
			var resources = Uno.UI.ContextHelper.Current?.Resources;
			;
#elif __IOS__
			ResourceHelper.ResourcesService = new Uno.UI.Services.ResourcesService(new[] { Foundation.NSBundle.MainBundle });
#endif
```

Then you can use `ResourceHelper.FindResourceString()` to access strings defined in your Resources.resw file.

Localized strings currently aren't supported in WASM.

**Comment by iosub** [comment]
Hi
I get this error with
Android.Content.Res.Resources.NotFoundException
#if __ANDROID__
			var a =ResourceHelper.FindResourceString(value);
                 return a;
                
#elif __IOS__
			var a =ResourceHelper.FindResourceString(value);
                 return a;
#else
                var resourceLoader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView();
                var a = resourceLoader.GetString(value);
               
                Debug.Write(a);
                return a;


on 
obj\Debug\MonoAndroid80\res\values I can see the strings.xml generated


Do I missing something??

Thanks

**Comment by iosub** [comment]
I found the issue

I had the defauld template file strings.xml o the shared project… I deleted and now is working

Thanks!
