### ISSUE TITLE
x:Uid not implemented on Android and IOs?

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#144]
Hi
is x:Uid implemented for Android and IOs… For my testing I see that is not implemented..

is there a workaround ?

Thanks

**Comment by Dissolute** [comment]
Uno supports x:Uid for localization in XAML, but requires some manual setup in addition to the [steps described here](https://github.com/nventive/Uno/issues/142#issuecomment-414775565).

You should already see a line in the .csproj head for each target platform similar to the following (assuming a solution created from the VSIX template as a starting point):

` <ResourcesDirectory>..\MyApp.Shared\Strings</ResourcesDirectory>
`
You need to add an ItemGroup to the csproj containing a line for each localization file:

``` xml
<ItemGroup>
    <XamlCodeGenerationResourceFiles Include="..\MyProject.Shared\Strings\en\Resources.resw" />
    <XamlCodeGenerationResourceFiles Include="..\MyProject.Shared\Strings\es\Resources.resw" />
    <XamlCodeGenerationResourceFiles Include="..\MyProject.Shared\Strings\fr\Resources.resw" />
   ...etc...
  </ItemGroup>
```

Once this is added it should work correctly.

**Comment by iosub** [comment]
Yes, you are right it works!!

Btw.
Can you do a fac file for localization support, including my tips that you have to delete the default strings.xml file on the shared project. It will help other.
thanks!
