### ISSUE TITLE
About OnItemsChanged method of ItemsControl have not Implemented

### ISSUE THREAD

**Issue by double28** [nventive/Uno#173]
In Uno the OnItemsChanged method of ItemsControl has not Implemented,but then Items property has    ItemsVectorChanged event; In UWP, the OnItemsChanged method has been implemented,but the ItemsVectorChanged event of Items property not work! why not use ItemsVectorChanged event to implement OnItemsChanged method in Uno? so we can use OnItemsChanged also in Uno!

**Comment by jeromelaban** [comment]
Thanks for the feedback! Indeed, that's correct, the method is not available, but will be once https://github.com/nventive/Uno/pull/175 is getting merged.

Items.VectorChanged should be working though. Do you have an example of what's not working ?

**Comment by double28** [comment]
Yes,you are right,it's work! I have tested it again.
