### ISSUE TITLE
Uno's Solution template has nuget inconsistencies

### ISSUE THREAD

**Issue by crogeniks** [nventive/Uno#19]
# Creating a new App with Uno's Solution template has nuget inconsistencies

Using UnoSolutionTemplate-1.30.3-wasm.vsix, the generated solution targets 
- 2 different versions 
- 1 unlisted nuget versions for Droid and iOS

# Functional impact

Nugets warning are generated as it has to fallback on a listed version for the Droid and iOS projects.

# Minimal repro steps 

- Download the latest UnoSolutionTemplate (UnoSolutionTemplate-1.30.3-wasm.vsix)
- Create a new Solution
- Open the Manage Packages for Solution Window

# Expected Results

All projects targets the same listed version of the nuget package. Preferably the latest version available.

# Actual result 

1.28.1-dev.2183 is unlisted

![image](https://user-images.githubusercontent.com/1256256/40786082-390b2d0a-64b8-11e8-8aab-17d8e45bc115.png)

**Comment by jeromelaban** [comment]
This has been adjusted with the latest vsix
