### ISSUE TITLE
WasmHttpHandler 'NetworkError when attempting to fetch resource'

### ISSUE THREAD

**Issue by Iresh32** [nventive/Uno#205]
## I'm submitting a...
Bug Report

## Current behavior
I am receiving an error - "NetworkError when attempting to fetch resource."  using the WasmHttpHandler.

## Expected behavior
It should return data the same as the UWP project.

## Minimal reproduction of the problem with instructions
I used the same code as the Demo as far as Creating the HTTPClient:
```
private static HttpClient CreateHttp()
        {
#if __WASM__

            var handler = new Uno.UI.Wasm.WasmHttpHandler();
            var httpClient = new HttpClient(handler);
#else

			var httpClient = new HttpClient();
#endif
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/json"));
            return httpClient;

        }

```

Then here is my task
```
     private async Task LoadStandings()
        {
            ObservableCollection<AdminClass> TempList = new ObservableCollection<AdminClass>();

            await Task.Delay(50);

            try
            {
                using (var httpClient = CreateHttp())
                {
                    var response = await httpClient.GetAsync(BaseApiUrl);
                    var responsePayload = await response.Content.ReadAsStringAsync();
                    TempList = JsonConvert.DeserializeObject<ObservableCollection<AdminClass>>(responsePayload);
                }

                MyStandingsListView.ItemsSource = null;
                MyStandingsListView.ItemsSource = TempList;
              
            }
            catch (Exception ex)
            {
              
            }
        }
```

I run the server.py and then receive this error in the browser.

FireFox - NetworkError when attempting to fetch resource.
Edge - Failed to fetch
Chrome - Failed to fetch

## Environment
```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [X ] 2017 (version: 15.8.2 )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by carldebilly** [comment]
We'll need a little more information to diagnose this problem:
1. May you confirm `BaseApiUrl` containts a valid url?
2. Please check in the _Network_ tab in the F12 debugger of your browser and check if the request is there.
3. Check the _Console_ tab in the F12 debugger of your browser for relevant error messages
4. Put a break point in the `send()` method of the `Uno.Http.HttpClient` class in javascript [check here](https://github.com/nventive/Uno/blob/master/src/Uno.UI.Wasm/WasmScripts/Uno.UI.js#L68) and observe if your request contains everything you need.

**Comment by Iresh32** [comment]
1. The BaseAPIURL is valid as this code works with the UWP project each time.
2.  My request is there and I can view the JSON response in the response tab. There is a lock with the line through it that says "The Connection used to fetch this resource was not secure"

3. Console tab had this information:

> The type [System.Object] is not known by the MetadataProvider, either add the Bindable attribute or add it to the TypeMetadataConfig.xml mono.js:1:34591
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 'MYURLWasHERE' (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]
> TypeError: "NetworkError when attempting to fetch resource." Uno.UI.js:86:25
> send/<
> http://localhost:8000/Uno.UI.js:86:25
> rejected
> http://localhost:8000/Uno.UI.js:56:47
> System.Exception: NetworkError when attempting to fetch resource. mono.js:1:34888
>   at Uno.Threading.FastTaskCompletionSource`1[T].GetResult () <0x2817440 + 0x0005e> in <8e2ada9f907f4b7ea607c51ccf167bc7>:0 mono.js:1:34888
>   at Uno.Threading.FastTaskCompletionSource`1[T].CreateAsyncTask () <0x2805378 + 0x000a4> in <8e2ada9f907f4b7ea607c51ccf167bc7>:0 mono.js:1:34888
>   at Uno.UI.Wasm.WasmHttpHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x27e90d8 + 0x00338> in <a127984bf11e450db17725016e9b3f97>:0 

4. I'm not really sure how to put a break point in the javascript. I thought I was not able to debug. This is the first time I've made a project with this platform.

**Comment by Iresh32** [comment]
Ok, thank you for the information. I really appreciate the help. I will work with the server from here.

**Comment by jeromelaban** [comment]
@amirvenus It seems that we're missing updates for the documentation, but `WasmHttpHandler` is not needed anymore. Use a normal `HttpHandler` instead.

**Comment by amirvenus** [comment]
> @amirvenus It seems that we're missing updates for the documentation, but `WasmHttpHandler` is not needed anymore. Use a normal `HttpHandler` instead.

I used the latest template in VS 2019 and changed the handler as advised but I am still getting these:
<img width="2310" alt="image" src="https://user-images.githubusercontent.com/5879559/138164631-3a7590f5-93da-420b-8078-242f1093bc46.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/5879559/138164653-a531b376-16cb-45a1-a956-e025bfa586ae.png">
