### ISSUE TITLE
Symbolicon cannot be used

### ISSUE THREAD

**Issue by HaoLife** [nventive/Uno#225]
I set the Winjs font according to the [document](https://github.com/nventive/Uno/blob/master/doc/articles/using-uno-ui.md), but I still can't use it Symbolicon

Set：

    <win:FontFamily x:Key="SymbolThemeFontFamily">Symbols</win:FontFamily>
    <android:FontFamily x:Key="SymbolThemeFontFamily">ms-appx:///Assets/Fonts/winjs-symbols.ttf#Symbols</android:FontFamily>

    <Style TargetType="FontIcon">
        <Setter Property="FontFamily" Value="{StaticResource SymbolThemeFontFamily}" />
    </Style>

xaml:

            <Button FontSize="12" HorizontalAlignment="Stretch"  VerticalAlignment="Stretch" Padding="0,5,0,1" Background="White">
                <StackPanel Orientation="Vertical">
                    
                    <SymbolIcon Symbol="Home" />
                    <TextBlock Text="home" Margin="0,3,0,0"/>
                </StackPanel>
            </Button>

            <Button  FontSize="12" HorizontalAlignment="Stretch"  VerticalAlignment="Stretch" Padding="0,5,0,1" Background="White">
                <StackPanel Orientation="Vertical">
                    <FontIcon Glyph="&#xE13D;"/>
                    <TextBlock Text="setting" Margin="0,3,0,0"/>
                </StackPanel>
            </Button>

FontIcon in accordance with the resources set above can take effect, but SymbolIcon will not be able to use, SymbolIcon internal Use FontIcon not valid, whether there is a way to use SymbolIcon , SymbolIcon in many places to use , such as: CommandBar

**Comment by jeromelaban** [comment]
This is curious indeed. On which platform are you testing this on ?

**Comment by HaoLife** [comment]
android

**Comment by HaoLife** [comment]
This problem is the wrong way to use fonts

> <not_android:FontFamily x:Key="SegoeThemeFontFamily">Segoe MDL2 Assets</not_android:FontFamily>
> <android:FontFamily x:Key="SegoeThemeFontFamily">ms-appx:///Assets/Fonts/SegMDL2.ttf#Segoe MDL2 Assets</android:FontFamily>


iOS adds fonts through info.plist files and uses them directly with font names
The UWP introduces fonts through the "fontfamily" Join font path and can be used at the same time through the font name
Android is used in a similar way to the UWP, but does not seem to be used by font names
