### ISSUE TITLE
Error can't render UI on wasm

### ISSUE THREAD

**Issue by MoonSmileDev** [nventive/Uno#235]
this code can't render as expect on Wasm
I run on Microsoft EDGE    

<Grid Background="White" Opacity="0.7">
        <StackPanel VerticalAlignment="Center" HorizontalAlignment="Center" Height="400" MaxHeight="400" Width="500" MaxWidth="700" CornerRadius="30,30,30,30" RequestedTheme="Dark">
            <StackPanel.Background>
                <AcrylicBrush/>
            </StackPanel.Background>
            <Grid HorizontalAlignment="Center" VerticalAlignment="Center">

                <TextBlock Text="Đăng Nhập" 
						VerticalAlignment="Top" 
						RenderTransformOrigin="0.493,0.5" 
						Margin="0,81,0,0" 
						Width="402"
                        HorizontalAlignment="Center" 
						Height="66" FontFamily="Viner Hand ITC" 
						FontSize="36" 
						FontWeight="Bold" 
						TextAlignment="Center" 
						TextDecorations="Underline" 
						FontStyle="Normal" 
						UseLayoutRounding="False" 
						RequestedTheme="Light"/>
                <TextBox x:Name="user"
                         Foreground="#FFAC09AC"
                         PlaceholderText="User"
                         Margin="0,175,4,-84" 
                         PlaceholderForeground="White" 
                         Background="#663A1212" 
                         VerticalAlignment="Stretch" 
                         RequestedTheme="Dark" FontSize="36" FontFamily="Algerian" TextWrapping="Wrap" />
                <PasswordBox x:Name="password"
                         
                         PlaceholderText="Password"
                         Margin="0,259,4,-168"  
                          
                         Background="#66000000" 
                         RequestedTheme="Dark" 
                         HorizontalAlignment="Stretch" FontSize="36" BorderBrush="#66999999" FocusVisualPrimaryBrush="Black" FocusVisualSecondaryBrush="#99FFFFFF" Foreground="White" FontFamily="Algerian" PasswordChanged="password_PasswordChanged" />
            </Grid>
        </StackPanel>
    </Grid>

**Comment by jeromelaban** [comment]
Thanks for the report!

The best way to troubleshoot this is to create a repro using the Visual Studio Uno Platform App template
, and post it here.

Also, could you post a screenshot of what you're seeing ?

**Comment by MoonSmileDev** [comment]
But when run on MicrosoftEdge.

![image](https://user-images.githubusercontent.com/39961250/46360733-3fa56c80-c696-11e8-95b1-f8d728d701c0.png)

**Comment by MoonSmileDev** [comment]
Oh... It works very good/…. I am sory because of my confusion... :(
