### ISSUE TITLE
SymbolIcon doesn't work on Android

### ISSUE THREAD

**Issue by weitzhandler** [nventive/Uno#273]
# Bug report

`SymbolIcon` doesn't render symbols on Android (and maybe also on Wasm/iOS).

Here's what it looks in UWP:

![image](https://user-images.githubusercontent.com/2716316/47036146-81e5a800-d184-11e8-934a-cb33294bad3a.png)

Whereas this is how it's rendered in Android:

![image](https://user-images.githubusercontent.com/2716316/47036066-4f3baf80-d184-11e8-86bb-79a3aaf296f2.png)

## Current behavior
Android cannot render `SymbolIcon`s properly.

## Expected behavior
Proper rendering of `SymbolIcon` on all platforms.

## Minimal reproduction of the problem with instructions

      <ToggleButton>
        <SymbolIcon Symbol="Play" />
      </ToggleButton>

## Environment
Android 8

### Nuget Package: 
Uno.UI

### Package Version(s): 
1.40.0

### Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

### Visual Studio
- [x] 2017 (version: 15.8.1)

Related: #225

**Comment by jeromelaban** [comment]
Provided the Symbols font is present, SymbolIcon will now work properly, the Visual Studio addin templates have the fonts already added.
