### ISSUE TITLE
Got a net::ERR_CACHE_MISS when in Release to Android

### ISSUE THREAD

**Issue by TonyHenrique** [nventive/Uno#29]
I put a 
` <WebView x:Name="wv1"  Source="https://www.google.com/"></WebView>`
and a 
```
                <Button x:Name="btn1" Click="Button_Click" >
                    <TextBlock>btn1</TextBlock>
                </Button>
```
and have this code 
```
        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            wv1.Navigate(new Uri("https://news.google.com"));
        }
```

If I deploy it in Debug to my LENOVO K10a40 (Android 6.0 API 23)  it works fine.
But If I deploy in Release to it, then this appears on the WebBrowser

`net::ERR_CACHE_MISS
`

**Comment by jeromelaban** [comment]
Have you added the INTERNET permission to your android manifest ?

 `<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by jeromelaban** [comment]
@TonyHenrique did you get past this issue ?

**Comment by TonyHenrique** [comment]
Thank you. After adding the INTERNET permission It works on **Release** configuration!
