### ISSUE TITLE
System.Net.HttpWebRequest cannot be used in Wasm.

### ISSUE THREAD

**Issue by xsteel2003** [nventive/Uno#30]
Because I need to get data from a Web server, it seems that many of the System.Net namespaces cannot be used in Wasm, such as System.Net.WebClient. (All code in UWP works)

**Comment by jeromelaban** [comment]
Thanks for your interest, you can use this to make HTTP calls: https://github.com/nventive/Uno.Playground/blob/80322aec3d759d009f6a900bca4a07bc63ae6a62/Uno.UI.Demo.Shared/Samples/Playground.xaml.cs#L487

You have to inject it at all call sites, since the BCL does not allow for changing it globally.

**Comment by xsteel2003** [comment]
Thank you very much, the CreateHttp() code works!

**Comment by jeromelaban** [comment]
Excellent, thanks !
