### ISSUE TITLE
App' does not contain a definition for 'InitializeComponent' 

### ISSUE THREAD

**Issue by Iresh32** [nventive/Uno#318]
I'm just starting out and I downloaded the QuickStart Demo app called MyApp. I launched that project and it fails on build.  

WASM is not availble
App' does not contain a definition for 'InitializeComponent' 
MainPage' does not contain a definition for 'InitializeComponent' 

I updated the NuGet Packets Uno.UI, Uno.WASM.Bootstrap, and Microsoft.NETCore.UniversalWindowsPlatform. 

Then rebuilt the project, and it still failed with the same errors. 
I'm running VS 15.7.6.

Any ideas?

**Comment by vskotatko** [comment]
This is still broken. I just installed VS 4.8.03752 and I get the XAML path error. If I go through the workaround, I can get it to display the XAML file and allow editing.

However, the build still fails with 'App' does not contain a definition for 'InitializeComponent' ...

This is preventing me from doing anything useful. As well, it is preventing nuget from updating packages.
