### ISSUE TITLE
Documentation links are not working when viewed from GitHub

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#327]
## I'm submitting a...
- Documentation 

## Current behavior
Links from https://github.com/nventive/Uno/blob/master/doc/index.md are not working when viewed on GitHub.

## Expected behavior
Should work for both the docs generated site, and GitHub.

**Comment by jeromelaban** [comment]
It does not seem to generate a proper link, the `~` works, but the link needs to be a `.md` not an `.html`. Is there a way for docfx to detect that in a link ?

**Comment by nvkarine** [comment]
I changed the links markup to MD syntax, which is converted to html markup on docfx build. Seems to do the trick.
