### ISSUE TITLE
[WASM] Autofac is unable to resolve types (DeclaredConstructors is empty)

### ISSUE THREAD

**Issue by paulovila** [nventive/Uno#375]
- Bug report in WASM
Autofac is unable to resolve types, when executing `type.GetTypeInfo().DeclaredContructors ` it returns empty, regardless that the public type has a default parameter-less public constructor, or no constructor at all
## Current behaviour

Given a class  
`public class A { public A() { } }`

When the WASM executes
`           System.Diagnostics.Debug.WriteLine($"Constructors : {typeof(A).GetTypeInfo().DeclaredConstructors.FirstOrDefault()}");`

It returns an empty collection

## Expected behavior
It should return the default constructor

## Environment
```
Release Version(s): 
Uno (master branch) ID	f9f441b63ddf0bed05582761e1bf473db7246d55	16/11/2018 01:56:58 +00:00

Affected platform(s):
- [X] WebAssembly

Visual Studio
- [X] 2017 Preview (version: )
```

**Comment by carldebilly** [comment]
Looks like your types are being _linked-out_ in the output assembly.

It's the same problem when using _NewtownSoft's JSON.NET_. Here's the documentation for it:
<https://github.com/nventive/Uno/blob/master/doc/articles/faq.md#i-get-errors-when-serializing-json-in-uno-wasm>

Alternatively you can also add the attribute `[Preserve]` on your class to prevent the linker from removing it in final assembly.

**Comment by paulovila** [comment]
Thanks @carldebilly  , I've added the relevant assemblies and types in the LinkerConfig.xml and now the constructors are being resolved
