### ISSUE TITLE
Is microsoft UWP toolkit supported?

### ISSUE THREAD

**Issue by JanabiSoft** [nventive/Uno#38]
I have tried to port my one of my existing UWP app to Uno platform but I couldn't enable UWP toolkit on any of the project 
in wasm project it says:
NU1202: Package Microsoft.Toolkit.Uwp.UI.Controls 2.2.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.Toolkit.Uwp.UI.Controls 2.2.0 supports: uap10.0 (UAP,Version=v10.0)
and in IOS:
NU1202: Package Microsoft.Toolkit.Uwp 3.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package Microsoft.Toolkit.Uwp 3.0.0 supports: uap10.0 (UAP,Version=v10.0)

**Comment by jeromelaban** [comment]
It is not yet supported, but you can follow this repo for updates: https://github.com/nventive/Uno.WindowsCommunityToolkit

**Comment by JanabiSoft** [comment]
thanks @jeromelaban for the explanation. Can you please publish an article about which frameworks, toolkits etc. that currently work without modification or with modification or not supported for example:
Syncfusion essential studio
Telerik UI
MVVM light
MVVM cross
Prism

**Comment by jeromelaban** [comment]
Support has improved for most of those frameworks. Missing are Telerik UI and MVVM Cross, I'll open issues for those two.
