### ISSUE TITLE
Path Stretch is incorrect

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#387]
## I'm submitting a...
- Bug report 

## Current behavior
https://github.com/nventive/Uno.Playground/blob/0de73abdca00028ad6fe8ccab046e0cd3265a38e/src/Uno.Playground.Shared/Samples/Shapes.xaml#L41 is not being displayed properly

## Expected behavior
The path should be scaled according to the Stretch property.

## Environment
Nuget Package: 1.42

**Comment by carldebilly** [comment]
Fixed.
