### ISSUE TITLE
The possibility of using webgl to show xaml on Wasm?

### ISSUE THREAD

**Issue by xsteel2003** [nventive/Uno#393]
See this link: https://github.com/liquidboy/XamlGL 

Will using WebGL have better performance than using HTML?

**Comment by jeromelaban** [comment]
What @yowl said. Theoratically, Uno could target WebGL (or another canvas-styled rendered) to have full fidelity, but it would be at the expense of some platform provided features that would need to be redeveloped.

This is a feature request that falls into the same bucket as supporting Gtk#, Qt or any other framework.

I've open #400 for that, feel free to follow it.
