### ISSUE TITLE
Navigation view control doesn't work

### ISSUE THREAD

**Issue by jkommeren** [nventive/Uno#4]
Would really like that one to work, I think its used a lot, especially since the Windows Template kit uses it now too.

I know this is because you've mentioned only porting part of the controls on Reddit , thought I'd mention it here too.

The alternative also doesn't work (hamburger view from UWP toolkit)

(I mean it doesn't compile)

**Comment by jeromelaban** [comment]
Thanks for the report !

At this point, Uno targets the Creators Update UWP version (14393) and NavigationView was introduced in the Fall Creators update (16299) which we do not support yet.

For the time being, you can use Frame and some modes of the SplitView controls for navigation.

**Comment by 165plo** [comment]
Is there ETA when Fall Creators update (16299) features will start to be supported?

**Comment by wind-rider** [comment]
Does it help that for Windows there is the [WinUI library nuget package](https://aka.ms/winui) now that fills the gap for those older windows versions?

**Comment by Dissolute** [comment]
> Does it help that for Windows there is the WinUI library nuget package now that fills the gap for those older windows versions?

Unfortunately since the Microsoft.UI.Xaml library is closed-source (like the base framework) this doesn't help much, since we can't modify it to target Uno like we can for open-source UWP libraries.

**Comment by JimGaleForce** [comment]
Any recommendations for /any/ navigation to work (even add ons that work with Uno), since both HamburgerMenu and NavigationView don't?

**Comment by weitzhandler** [comment]
@davidjohnoliver 

> Unfortunately since the Microsoft.UI.Xaml library is closed-source (like the base framework) this doesn't help much, since we can't modify it to target Uno like we can for open-source UWP libraries.

Looks like WinUI is open source, [here](https://github.com/Microsoft/microsoft-ui-xaml) is its repo. I think WinUI makes for a better ground than UWP in general, no?
