### ISSUE TITLE
Getting HttpClient to work with Wasm

### ISSUE THREAD

**Issue by davidlsharp1** [nventive/Uno#42]
I think there's a common issue with mono wasm and HttpClient.  I get a ERROR: Operation is not supported on this platform.

Blazer was able to get it working but its not a normal HttpClient.  HttpClient doesnt work with Ooui yet either.  Is there a work around that Ive missed?

**Comment by davidlsharp1** [comment]
@zbigniew-gajewski   thanks, I'll check it out.

**Comment by davidlsharp1** [comment]
So does this mean that I should be able to copy that CreateHttp method into my ViewModel?

The WASM part is giving me an error:

`The type or namespace name 'WasmHttpHandler' does not exist in the namespace 'unoDemo98.Wasm' (are you missing an assembly reference?)
`

I'm not getting any help with the quick actions .  Any idea what I am missing?

```
        private static HttpClient CreateHttp()
        {
#if __WASM__
            var handler = new Wasm.WasmHttpHandler();
			var httpClient = new HttpClient(handler);
#else
            var httpClient = new HttpClient();

#endif
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/json"));
            return httpClient;
        }
```

**Comment by jeromelaban** [comment]
@davidlsharp1 the [WasmHttpHandler](https://github.com/nventive/Uno/blob/26c5cc5992cae3c8c25adf51eb77ca4b0dd34e93/src/Uno.UI.Wasm/WasmHttpHandler.cs#L16) is part of the Uno.UI package. Is it included in your project ?

**Comment by davidlsharp1** [comment]
Hi @jeromelaban.  Yes, I added the Uno.UI nuget.

**Comment by jeromelaban** [comment]
@davidlsharp1 I missed the real reason. You have a namespace called `wasm` and it's taking precedence over `Uno.UI.Wasm`. Try qualifying it completely `Uno.UI.Wasm.WasmHttpHandler`.

**Comment by davidlsharp1** [comment]
@jeromelaban  Ah ok.  I'll give it a try and report back. Thanks!

**Comment by jeromelaban** [comment]
Support has significantly improved, and this issue has been superseded by https://github.com/nventive/Uno/issues/161

**Comment by MelbourneDeveloper** [comment]
@jeromelaban , Hi. I'd like to see if I can get my rest client library working on Platform Uno:
https://github.com/MelbourneDeveloper/RestClient.Net

It's just a wrapper for HttpClient. So I'm just wondering... Can we use HttpClient yet? Or, do we use this code mentioned in #161?

```cs
var httpMessageHandler = Type
  .GetType("System.Net.Http.HttpClient, System.Net.Http")
  .GetField(
    "GetHttpMessageHandler",
    BindingFlags.Static | BindingFlags.NonPublic
  );

httpMessageHandler.SetValue(
  null,
  (Func<HttpMessageHandler>)(() => new Uno.UI.Wasm.WasmHttpHandler())
);
```

I'd be happy to write a version of RestClient.Net that wraps this code so that it's easy to hit a REST service. Is this the recommended approach?

**Comment by yowl** [comment]
I don't think it needs to be that complicated I have 
```
#if __WASM__
            HttpClient = new HttpClient(new WasmHttpHandler());
#else
            HttpClient = new HttpClient(new HttpClientHandler());
#endif
```
Which is enough for UWP and WASM.  Does that not work for ios/android?

**Comment by MelbourneDeveloper** [comment]
@yowl that looks better.

@jeromelaban , how does building libraries from wasm via Uno work? Can Uno directly reference a DLL? A NuGet? Is there documentation on to do this?

**Comment by garethjhewitt** [comment]
I can't seem to get this to work at all.

Using the latest uno template I edit the simple mainpage with a button and label like so:


        public MainPage()
        {
            this.InitializeComponent();
            btn.Click += OnClicked;
        }

        private async void OnClicked(object sender, RoutedEventArgs e)
        {
            lbl.Text = "clicked";
            try
            {
                var wc = new System.Net.Http.HttpClient(new Uno.UI.Wasm.WasmHttpHandler());
                //var client = new System.Net.WebClient();
                var response = await wc.GetStringAsync(new Uri("http://html5rocks-cors.s3-website-us-east-1.amazonaws.com/index.html"));
                lbl.Text = response; 
            }
            catch(Exception ex)
            {
                lbl.Text = ex.Message;
            }
        }

I can't get any variation (including the above) of this to work at all for wasm. Am I missing something?
