### ISSUE TITLE
Wasm - MvvmLight adaptation issues

### ISSUE THREAD

**Issue by zbigniew-gajewski** [nventive/Uno#44]
I am testing **MvvmLight** framework with **Wasm** project, but it seems like MvvmLight in Wasm is not yet fully supported. Issues I found:

1. **MvvmLight** package has **.Net Standard 1.0** version. After adding **MvvmLight package** to **Wasm** project, the reference shows no warning, but `using GalaSoft.MvvmLight` in c# code doesn't work (the project doesn't compile):

![mvvmlightstd10](https://user-images.githubusercontent.com/32226444/41498090-a9dcbc02-7164-11e8-9e66-8008afca3ad8.png)

After preparing **.Net Standard 2.0 'MvvmLight' package**,  `using GalaSoft.MvvmLight` can be used:

![mvvmlightstd20](https://user-images.githubusercontent.com/32226444/41498109-37936a14-7165-11e8-9d7e-400c1679614f.png)

Is that mean, that **Wasm project** (which is targeted to **.Net Standard 2.0**) can work only with packages targeted to **.Net Standard 2.0**? Or maybe there is any configuration which would allow to add **.Net Standard 1.0** package to **Wasm .Net Standard 2.0** project? 

2. In order to implement ViewModelLocator, **CommonServiceLocator 2.0.3** package has to be added to Wasm project. After adding it and rebuilding the **Wasm project**, compilation shows error:

![commonservicelocatorerror](https://user-images.githubusercontent.com/32226444/41498168-adf7f426-7166-11e8-84c4-a04311dca9bc.png)

Alternative working solution is not to install CommonServiceLocator in Wasm project and in Shared project use code like this:

```
#if __WASM__
using Microsoft.Practices.ServiceLocation;
#else 
using CommonServiceLocator;
#endif
```

3. In **.Net Standard** version of **MvvmLight**, **NavigationService** and **DialogService** are not implemented, so they can't be used is Wasm project. This is because in MvvmLight (UWP) both classes  uses three platform-specific UI elements such as: **_MessageDialog, Frame, Window_**. Which controls from Uno/Wasm library should be used to correctly replace **MessageDialog, Frame, Window** and correctly implement NavigationService and DialogService targeting **Uno/Wasm** platform?

**Comment by jeromelaban** [comment]
Thanks for filing this issue!

Have you tried using 
The [Uno.GalaSoft.MvvmLight.Platform](https://www.nuget.org/packages/Uno.GalaSoft.MvvmLight.Platform/) and 
[Uno.GalaSoft.MvvmLight](https://www.nuget.org/packages/Uno.GalaSoft.MvvmLight/) ? Those two packages are compatible with Uno, and their platform specific services are implemented.

**Comment by zbigniew-gajewski** [comment]
Perfect! It works!
I wasn't aware, that Uno adapter for MvvmLight exists. Thank you! 
So it seems like this issue is solved and can be closed.

**Comment by jeromelaban** [comment]
Excellent! We're in contact with @lbugnion to avoid getting this included in the main nuget.
