### ISSUE TITLE
Enable Uno Platform Solution Templates to work on Visual Studio 2019 (Preview)

### ISSUE THREAD

**Issue by TonyHenrique** [nventive/Uno#475]
- Feature request:
Enable **Uno Platform Solution Templates** to work on Visual Studio 2019 (Preview)

I tried to install this on Visual Studio 2019, but no success:
https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin

On Visual Studio 2017 it is listed and installs

**Comment by jeromelaban** [comment]
Fixed by #420
