### ISSUE TITLE
QuickStart Wasm doesn't work with the latest packages

### ISSUE THREAD

**Issue by godrose** [nventive/Uno#498]
## I'm submitting a...

-- - Regression (a behavior that used to work and stopped working in a new release)
  
 

## Current behavior

'Loading' is displayed without any progress

## Repro steps
Clone Samples.QuickStart
Update to the latest versions of Uno.UI and Was.Bootstrap
Start wasm using http-server

**Expected**
'Hello world' is displayed

**Actual**
'Loading' is displayed without any progress

## Environment

```
Nuget Package: 
Uno.UI 1.42.0
Wasm dev137
Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
This seems unusual. Which browser are you using?

Could you also look at the debugging console and tell us if there are warning or error messages ?

**Comment by godrose** [comment]
Chrome in Windows

**Comment by jeromelaban** [comment]
Could you try with this pre-release ? This may have been addressed already: https://github.com/nventive/Uno/releases/tag/1-43-0-dev-657

**Comment by ghuntley** [comment]
QuickStart at `master` which is `<PackageReference Include="Uno.UI" Version="1.43.1" />` does not reproduce this with WASM in google chrome. Going to mark this `triage/needs-information` and close this out if we don't hear back in the future.

![85479AFF-347E-464E-B939-3596A061F21F](https://user-images.githubusercontent.com/127353/58490692-f5d33e80-81b0-11e9-97a6-ec9a8832d321.GIF)

**Comment by ghuntley** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/nventive/Uno/issues/498#issuecomment-496568356. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
