### ISSUE TITLE
The Uno.UI package break UWP compilation when using SDK 16299 and later

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#5]
This is caused by the fact that Uno.UI supports netstandard 2.0, and Windows SDK 16299 added support for it, making the Uno.UI source generator run on UWP.

As a workaround, in the UWP project, add the following line (such as [this one](https://github.com/nventive/Uno.Playground/blob/80322aec3d759d009f6a900bca4a07bc63ae6a62/Uno.UI.Demo.UWP/Uno.UI.Demo.UWP.csproj#L25)):

```
<PackageReference Include="Uno.UI" ExcludeAssets="build">
      <Version>1.29.1-aobfwasm.2834</Version>
</PackageReference>
```

To exclude the Uno.UI source generator from the build pipeline.

**Comment by TonyHenrique** [comment]
It worked.


```
<PackageReference Include="Uno.UI" ExcludeAssets="build">
      <Version>1.29.1-aobfwasm.2834</Version>
</PackageReference>
```

**Comment by jeromelaban** [comment]
@carldebilly the package is really broken :) We have to fix it.

**Comment by jeromelaban** [comment]
Fixed as part of the sources release.
