### ISSUE TITLE
Android build fails due to icon issues

### ISSUE THREAD

**Issue by JanabiSoft** [nventive/Uno#50]
android build fails showing the following error:

Error: Originally defined here.	    ...\res\drawable-mdpi-v4\square44x44logo.altform-unplated_targetsize-16.png

Error	: Resource entry square44x44logo is already defined.	...\drawable-mdpi-v4\square44x44logo.altform-unplated_targetsize-256.png

these 2 error show multiple times for all square44x44logo images

development environment: windows 10 pro 17134, VS community 15.7.1

**Comment by miguelrochefort** [comment]
You must not include UWP-specific assets (e.g., Square44x44Logo) in the shared project. Leave them in the UWP head.

You can find more information about shared assets here: https://github.com/nventive/Uno/blob/master/doc/articles/working-with-assets.md

**Comment by JanabiSoft** [comment]
Thanks for the help.
There is no way to know that in advance,
that's Why it is important for you guys to publish a detailed walkthrough about porting a working UWP app to Uno platform and to keep in mind this app may use 3rd party components like UWP community toolkit, syncfusion controls, MVVMcross, it will be very helpful for developers specially your platform is new to us and there is a scarcity of articles, samples and guides about the platform.
also a documentation section in the official website will be greatly helpful.

**Comment by jeromelaban** [comment]
Significant changes have been made to the resource generation tool. If this issue is still valid, please open a new one, thanks !
