### ISSUE TITLE
Relationship to fuse-open/uno, if any?

### ISSUE THREAD

**Issue by rhencke** [nventive/Uno#58]
[Fuse's Uno](https://github.com/fuse-open/uno) is a recently open-sourced C# cross-platform API, providing a C# dialect that cross-compiles to both C++11 with ref-counting instead of GC (iOS and Android), but also cross-compiles to CI targeting .NET.  As far as I can tell, this Uno is also a recently open-sourced C# cross-platform API, but is not a compiler itself, but rather a framework for UWP applications to natively run/be developed for iOS, Android, .NET, and the web?

I wasn't sure if the two efforts were independent or not, and it was a little confusing at first.  I brought it up here in case I might not be the only one, and maybe it'd merit a small blurb in the README or such.

Or maybe the two projects could join forces and we could have Uno running atop Uno. :)

**Comment by MatFillion** [comment]
Hi @rhencke ,

Sorry for the late reply but there are no relations between Uno platform and Fuse's Uno. They are independent.

Your description of our Uno platform is correct, it is a framework for UWP applications to run natively on iOS, Android and WebAssembly. We are leveraging Xamarin (for iOS/Android) and Mono to do so. (more info: https://platform.uno/#Architecture)
