### ISSUE TITLE
Implement MediaElement on every platforms

### ISSUE THREAD

**Issue by Poppyto** [nventive/Uno#59]
MediaElement (or MediaPlayer+MediaPlayerElement) is a difficult control to implement (much more than other, because of SMTC) but without it, Uno seems unusable to me because all my works use MediaElement.
The solution has to work on everyplatform (even WASM with <video>).
Obviously some advanced features can't work (like DLNA casting) on other platforms but basic functionnality could be a good start.

**Comment by queequac** [comment]
Same for me, my primary app relies heavily on MediaElement and integrating the host platform's player on each target platform would be big effort (each developer would have to do then over and over again).

Especially supporting custom transport controls would be a big plus.

**Comment by jeromelaban** [comment]
This issue has been superseded by https://github.com/nventive/Uno/issues/154, you can follow the progress there, which has been significant!
