### ISSUE TITLE
Does Uno support Prism?

### ISSUE THREAD

**Issue by wind-rider** [nventive/Uno#60]
Does Uno support the Prism framework?

**Comment by jeromelaban** [comment]
Prism is not supported yet, but should soon be.

**Comment by wind-rider** [comment]
Nice!

**Comment by weitzhandler** [comment]
For me, Prism is the only part holding me back from start using Uno, as I'm really used to Prism, especially with anything bigger than a toy project.

**Comment by jeromelaban** [comment]
Prism is now available here: https://github.com/nventive/Uno.Prism.

Let us know what you think !

**Comment by weitzhandler** [comment]
1. Please have the [forked Prism repo](https://github.com/nventive/Uno.Prism) have its own issues (enable it in the fork settings)
2. Please add some basic instructions on how to get Prism to work with Uno. Are there any templates etc?
3. A basic explanation on what's the difference between the various [Uno.Prism NuGet packages](https://github.com/nventive/Uno.Prism#uno-platform-port-of-xaml-behaviors)

Thanks a lot!

**Comment by weitzhandler** [comment]
I'd vote to open this issue.
A fork of Prism isn't a solution. What does it take to make the main Prism work with Uno Wasm? This is my number 1 problem of starting projects with Uno.

**Comment by jeromelaban** [comment]
See https://github.com/nventive/Uno.Prism/pull/9 as a tentative to contribute to the main Prism library.

**Comment by weitzhandler** [comment]
@jeromelaban 
WOW, that is incredible!
Thank you SOO much for the awesome work!

**Comment by weitzhandler** [comment]
https://github.com/PrismLibrary/Prism/pull/2054
