### ISSUE TITLE
The #160  didn't be merged in release 1.43.1

### ISSUE THREAD

**Issue by Daoting** [nventive/Uno#665]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one) 
Didn't support for AddHandler and RemoveHandler
Didn't support for virutal event methods. 
The old version supported.
Did the [#160](https://github.com/nventive/Uno/pull/160) not be merged in release 1.43.1?

 

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
Indeed, this PR did not get merged in the 1.43.0 release. This release too longer to stabilize, which is why we started before the Routed Events PR as it is a massive change. It will most likely get integrated in the 1.44 release.
