### ISSUE TITLE
Building WASM sample project fails in case the project path name holds blanks

### ISSUE THREAD

**Issue by DierkDroth** [nventive/Uno#666]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)
 

## Current behavior
Building the WASM head of the sample project as per [here](https://github.com/nventive/Uno.QuickStart) fails if the project path holds blanks (not sure if there is a similar issue on other non-alphanumeric characters). 

Here is the exception in VS output (note the truncated path name in the exception message):
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error :
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error : Unhandled Exception: System.Exception: Could not resolve C:\Users\DDroth\Documents\Visual
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error :    at Driver.Resolve(String asm_name, AssemblyKind& kind)
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error :    at Driver.Run(String[] args)
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error :    at Driver.Main(String[] args)
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error : System.Exception: Failed to generate wasm layout
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error :    at Uno.Wasm.Bootstrap.ShellTask_vc25c613b5190954144284486cfec2056d1820375.RunPackager()
1>C:\Users\DDroth\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.137\build\Uno.Wasm.Bootstrap.targets(101,3): error :    at Uno.Wasm.Bootstrap.ShellTask_vc25c613b5190954144284486cfec2056d1820375.Execute()

## Expected behavior
Building the WASM sample should work no problem

## Minimal reproduction of the problem with instructions
- create new sample project in a path which holds a blank (like the default VS projects path)
- in solution explorer: Uno.Wasm -> right click -> Rebuild

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ x] 2017 (version: latest)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
This is an issue that has been addressed in https://github.com/nventive/Uno.Wasm.Bootstrap/pull/50 of the `Uno.Wasm.Bootstrapper` package. You can update both Uno.UI and the `Uno.Wasm.Bootstrapper` to the latest dev branch to fix this.

We'll update the quickstart repo to address this.

**Comment by DierkDroth** [comment]
Excellent!. Thanks
