### ISSUE TITLE
Camera and Photos APIs

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#68]
How can I access the camera, take a picture, also how can I access Photos / files in phone? and Post to a REST WebAPI?

It would be good to have this included in the sample app.

Moved from https://github.com/nventive/Uno.Playground/issues/9

**Comment by jeromelaban** [comment]
The camera APIs have not been implemented yet, but the rest API can be called using HttpClient. See this thread for details https://github.com/nventive/Uno/issues/30.

**Comment by danielkornev** [comment]
Any good suggestions on how to use camera API through Xamarin?

**Comment by danielkornev** [comment]
@jeromelaban made this example here:
https://github.com/nventive/Uno.Samples/tree/master/UI/AndroidCustomCamera

**Comment by jeromelaban** [comment]
This is actually better than that, https://github.com/nventive/Uno/pull/251 introduces Windows.Media.Capture.CameraCaptureUI for iOS/Android. 

The above sample show how to do it in a custom way, directly with activities for android only.

**Comment by brendanalexdr** [comment]
So...I guess this feature still doesn't exist?  I need to create an app that reads QR codes and was thinking of delving into it with uno framework.

**Comment by MarkLFT** [comment]
> So...I guess this feature still doesn't exist? I need to create an app that reads QR codes and was thinking of delving into it with uno framework.

@brendanalexdr I am also looking for a solution to read QR codes, but also to read the codes form passports, did you find a solution?

**Comment by jeromelaban** [comment]
Let's continue here: https://github.com/unoplatform/uno/discussions/12851
