### ISSUE TITLE
Tapped handler are invoked twice

### ISSUE THREAD

**Issue by dr1rrb** [nventive/Uno#691]
## I'm submitting a...
- Bug report

## Current behavior
When registering a `Tapped` event handler on a `Button` in XAML, the handler is invoked twice when we click on the button.

## Expected behavior
It's  being invoked only once.

## Minimal reproduction of the problem with instructions
```xaml
<Button Content="Animate" Tapped="StartAnimation" />
```
```csharp
private void StartAnimation(object sender, TappedRoutedEventArgs e)
{
     Console.WriteLine("Tapped");
}
```
cf. `DoubleAnimation_BeginTime` in Uno samples.

## Environment
```
Nuget Package: Uno.UI
Package Version(s): _latest dev_ 
Affected platform(s):
- [?] iOS
- [?] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio: _irrelevant_
Relevant plugins: _none_ 
```

**Comment by carldebilly** [comment]
Fix has been merged to master....
