### ISSUE TITLE
The template 'Uno App Solution' 1.30.1 generates an invalid UWP appmanifest.xml

### ISSUE THREAD

**Issue by MarkStega** [nventive/Uno#7]
The generated appmanifest.xml for the UWP project has the following:

`  <Identity Name="$guid1$" Publisher="CN=nventive" Version="1.0.0.0" ProcessorArchitecture="x86" />
  <mp:PhoneIdentity PhoneProductId="1897f84c-689e-44d3-a8b7-c521a62818ae" PhonePublisherId="00000000-0000-0000-0000-000000000000" />
  <Properties>
    <DisplayName>$targetnametoken$</DisplayName>
    <PublisherDisplayName>$targetnametoken$</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
`

The $guid1$ generates the error in the build, but the $targetnametoken$ also appears to need expansion

**Comment by jeromelaban** [comment]
Thanks mark, indeed, this is missing.

**Comment by MarkStega** [comment]
It's an easy fix if you want to document without rushing a release - Just edit the Package.Appmanifest solution item and fill in sensible values where the $toekn$ entries are located...

**Comment by jeromelaban** [comment]
Sure, manipulating the package works as well :) I've updated to 1.30.3, which fixes this.
