### ISSUE TITLE
Nested styles fail to build for Droid and Wasm if placed in App.xaml

### ISSUE THREAD

**Issue by peternary** [nventive/Uno#706]
## I'm submitting a...

- Regression (a behavior that used to work and stopped working in a new release)

## Current behavior
If you include a named style whose template contains another named style Wasm and Droid both fail to build with the error "The name 'Loading' does not exist in the current context"

## Expected behavior
Projects should build and style be applied as appropriate

## Minimal reproduction of the problem with instructions

Create a new project, and in the App.xaml add the following:
```
<Application.Resources>
	<Style x:Key="CustomTextBox" TargetType="TextBox" >
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="TextBox">
					<Grid>
						<Grid.Resources>
							<Style x:Name="TestStyle" TargetType="Button">
								<Setter Property="Template">
									<Setter.Value>
										<ControlTemplate TargetType="Button">
											<Grid>
												<TextBlock Text="Sample"/>
											</Grid>
										</ControlTemplate>
									</Setter.Value>
								</Setter>
							</Style>
						</Grid.Resources>
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
</Application.Resources>
```
Add a TextBox to MainPage.xaml that uses the defined style and attempt to build for either Droid or Wasm.

## Environment

Nuget Package: Uno.UI

Package Version(s): 1.44.0-dev.1070

Affected platform(s):
- [ ] iOS
- [X] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [X] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by carldebilly** [comment]
I just found this bug is caused by the `x:Name` in the 2nd level style. If you replace it with a `x:Key`, you won't get that compilation error.
