### ISSUE TITLE
Failed to resolve SymbolIcon

### ISSUE THREAD

**Issue by paulovila** [nventive/Uno#713]
Bug report 
## Current behaviour
When I add a reference to the nuget package "Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="3.1.0-build.68.g1c44fa8ae7" The build fails with the following error:

_.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.58\build\Uno.Wasm.Bootstrap.targets(33,3): error : MarkException: Error processing method: 'System.Void Microsoft.Toolkit.Uwp.UI.Controls.__Resources._SlidableListItem_1d281c723c2c9317e7ef2ea0816c3828_SlidableListItemRDSC0/<>c::<Build>b__0_4(Windows.UI.Xaml.Controls.SymbolIcon)' in assembly: 'Microsoft.Toolkit.Uwp.UI.Controls.dll'
.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.58\build\Uno.Wasm.Bootstrap.targets(33,3): error : ResolutionException: Failed to resolve Windows.UI.Xaml.DependencyProperty Windows.UI.Xaml.Controls.SymbolIcon::get_SymbolProperty()_

## Expected behavior
The application should build

## Environment

```
Nuget Package(s): 
"Uno.Microsoft.Toolkit" Version="3.1.0-build.68.g1c44fa8ae7"
"Uno.Microsoft.Toolkit.Uwp" Version="3.1.0-build.68.g1c44fa8ae7"
"Uno.Microsoft.Toolkit.Uwp.UI" Version="3.1.0-build.68.g1c44fa8ae7"
"Uno.Microsoft.Toolkit.Uwp.UI.Animations" Version="3.1.0-build.68.g1c44fa8ae7"
"Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="3.1.0-build.68.g1c44fa8ae7"
"Uno.Microsoft.Xaml.Behaviors.Interactivity" Version="2.0.1-uno.28"
"Uno.UI" Version="1.42.0-dev.376"
"Uno.Wasm.Bootstrap" Version="1.0.0-dev.58"

Package Version(s): 

Windows 10 Build Number:
- [x] Insider Build (build number: )

App min and target version:
- [x] Insider Build (xxxxx)

Visual Studio 
- [ ] 2017 (version: )
- [x] 2017 Preview (version: )

```

**Comment by jeromelaban** [comment]
Fixed as part of https://github.com/nventive/Uno.WindowsCommunityToolkit/pull/29
