### ISSUE TITLE
WASM Debug does not work on latest builds

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#724]
Wasm Debug on Chrome  does not work on latest build of Uno

## I'm submitting a...

 Regression (a behavior that used to work and stopped working in a new release) 
  
 

## Current behavior
Debugging Wasm does not work on latest Uno Builds on chrome no .dll are loaded on the "Sources" tab using Shift+Alt+D

## Minimal reproduction of the problem with instructions
1.- Create a new solution using Uno template 1.43.1
Uno Version:
"Uno.UI" Version="1.43.1" 
"Uno.Wasm.Bootstrap" Version="1.0.0-dev.137" 

2.- Add  MonoRuntimeDebuggerEnabled true to the project file
3.-Open chrome with "%programfiles(x86)%\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 http://localhost:solutionPort/
4.- Shift+Alt+D
5.- on the source tab you can see all the dll loaded and you can set breakpoint
Console log
Loaded: netstandard.dll
mono.js:1 Loaded: App1.Wasm.pdb
mono.js:1 Loaded: System.Core.pdb
mono.js:1 Loaded: Mono.Security.pdb
mono.js:1 Loaded: Mono.Security.dll
mono.js:1 Loaded: App1.Wasm.dll
mono.js:1 Loaded: System.pdb
mono.js:1 Loaded: System.Numerics.dll
mono.js:1 Loaded: System.Numerics.pdb
mono.js:1 Loaded: System.Core.dll
mono.js:1 Loaded: System.Transactions.dll
mono.js:1 Loaded: System.Xml.pdb
mono.js:1 Loaded: System.Transactions.pdb
mono.js:1 Loaded: System.Drawing.pdb
mono.js:1 Loaded: System.IO.Compression.pdb
mono.js:1 Loaded: System.IO.Compression.FileSystem.dll
mono.js:1 Loaded: System.IO.Compression.FileSystem.pdb
mono.js:1 Loaded: System.Net.Http.pdb
mono.js:1 Loaded: System.Xml.Linq.pdb
mono.js:1 Loaded: System.Drawing.dll
mono.js:1 Loaded: mscorlib.pdb
mono.js:1 Loaded: System.IO.Compression.dll
mono.js:1 Loaded: System.Net.Http.dll
mono.js:1 Loaded: System.ComponentModel.Composition.pdb
mono.js:1 Loaded: System.ServiceModel.Internals.pdb
mono.js:1 Loaded: System.Web.Services.pdb
mono.js:1 Loaded: System.Xml.Linq.dll
mono.js:1 Loaded: System.ComponentModel.Composition.dll
mono.js:1 Loaded: System.ServiceModel.Internals.dll
mono.js:1 Loaded: System.Web.Services.dll
mono.js:1 Loaded: System.Runtime.Serialization.pdb
mono.js:1 Loaded: System.Data.pdb
mono.js:1 Loaded: System.dll
mono.js:1 Loaded: Uno.Xaml.dll
mono.js:1 Loaded: Uno.Foundation.pdb
mono.js:1 Loaded: Uno.Foundation.dll
mono.js:1 Loaded: System.Runtime.Serialization.dll
mono.js:1 Loaded: System.Runtime.dll
mono.js:1 Loaded: System.Resources.ResourceManager.dll
mono.js:1 Loaded: System.Collections.Concurrent.dll
mono.js:1 Loaded: Microsoft.Extensions.Logging.Abstractions.dll
mono.js:1 Loaded: Uno.UI.pdb
mono.js:1 Loaded: System.Collections.dll
mono.js:1 Loaded: System.Linq.dll
mono.js:1 Loaded: System.Globalization.dll
mono.js:1 Loaded: System.Reflection.dll
mono.js:1 Loaded: System.Runtime.Extensions.dll
mono.js:1 Loaded: System.Threading.dll
mono.js:1 Loaded: Microsoft.Practices.ServiceLocation.pdb
mono.js:1 Loaded: Microsoft.Practices.ServiceLocation.dll
mono.js:1 Loaded: System.Reflection.Emit.Lightweight.dll
mono.js:1 Loaded: Microsoft.Extensions.Logging.dll
mono.js:1 Loaded: System.Reflection.Emit.ILGeneration.dll
mono.js:1 Loaded: Microsoft.Extensions.DependencyInjection.Abstractions.dll
mono.js:1 Loaded: System.Linq.Expressions.dll
mono.js:1 Loaded: System.ComponentModel.dll
mono.js:1 Loaded: System.Threading.Tasks.dll
mono.js:1 Loaded: System.Numerics.Vectors.dll
mono.js:1 Loaded: System.Numerics.Vectors.pdb
mono.js:1 Loaded: Uno.UI.Wasm.pdb
mono.js:1 Loaded: WebAssembly.Bindings.dll
mono.js:1 Loaded: System.Diagnostics.Debug.dll
mono.js:1 Loaded: Uno.UI.Wasm.dll
mono.js:1 Loaded: Uno.Xaml.pdb
mono.js:1 Loaded: System.Collections.Immutable.dll
mono.js:1 Loaded: System.Xml.dll
mono.js:1 Loaded: Uno.Core.dll
mono.js:1 Loaded: System.Data.dll
mono.js:1 Loaded: Uno.pdb
mono.js:1 Loaded: mscorlib.dll
mono.js:1 Loaded: Uno.UI.dll
mono.js:1 Loaded: Uno.dll
mono.js:1 initializing mono runtime
mono.js:1 DEBUGGING ENABLED
mono.js:1 >>mono_wasm_runtime_ready
uno-bootstrap.js:101 Done loading the BCL
uno-bootstrap.js:116 Loading dependency (jquery-pep)
uno-bootstrap.js:116 Loading dependency (setImmediate)
uno-bootstrap.js:116 Loading dependency (Uno.UI)
uno-bootstrap.js:116 Loading dependency (AppManifest)
uno-bootstrap.js:109 Loaded dependency (Uno.UI)
uno-bootstrap.js:172 Debugging hotkey: Shift+Alt+D (when application has focus)
mono.js:1 Symbol file LoadedFromMemory is not a mono symbol file
mono.js:1 >>>mono_wasm_get_loaded_files

=================================

Update Uno nuget to:
"Uno.UI" Version="1.45.0-dev.1110" 
Uno.Wasm.Bootstrap" Version="1.0.0-dev.238" 
1.- Run the wasm project
2.-Open chrome with "%programfiles(x86)%\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 http://localhost:solutionPort/
3.- Shift+Alt+D
4.- No Dll are loaded and not source code
console log
Registering service worker now
uno-bootstrap.js:444 Service Worker Registered
uno-bootstrap.js:11 Setting MONO_GC_PARAMS=soft-heap-limit=512m,nursery-size=64m,evacuation-threshold=66,major=marksweep
uno-bootstrap.js:11 Setting MONO_LOG_LEVEL=debug
uno-bootstrap.js:11 Setting MONO_LOG_MASK=gc
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_MONO_RUNTIME_CONFIGURATION=release
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_MONO_RUNTIME_MODE=Interpreter
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_LINKER_ENABLED=True
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_DEBUGGER_ENABLED=True
mono.js:1 Loaded: Mono.Security.pdb
mono.js:1 Loaded: System.Numerics.dll
mono.js:1 Loaded: System.Drawing.Common.dll
mono.js:1 Loaded: System.Numerics.pdb
mono.js:1 Loaded: Mono.Security.dll
mono.js:1 Loaded: System.Drawing.Common.pdb
mono.js:1 Loaded: System.Net.Http.pdb
mono.js:1 Loaded: Uno.Foundation.dll
mono.js:1 Loaded: Uno.Foundation.pdb
mono.js:1 Loaded: Microsoft.Extensions.Logging.Abstractions.dll
mono.js:1 Loaded: Uno.Core.dll
mono.js:1 Loaded: Microsoft.Practices.ServiceLocation.dll
mono.js:1 Loaded: Microsoft.Extensions.Logging.dll
mono.js:1 Loaded: Uno.pdb
mono.js:1 Loaded: Uno.UI.Wasm.pdb
mono.js:1 Loaded: System.Net.Http.dll
mono.js:1 Loaded: WebAssembly.Bindings.dll
mono.js:1 Loaded: Uno.Xaml.dll
mono.js:1 Loaded: MySaaSPlace.Wasm.pdb
mono.js:1 Loaded: System.Collections.Immutable.dll
mono.js:1 Loaded: Uno.dll
mono.js:1 Loaded: System.Core.pdb
mono.js:1 Loaded: Uno.UI.Wasm.dll
mono.js:1 Loaded: System.pdb
mono.js:1 Loaded: System.Xml.pdb
mono.js:1 Loaded: System.Core.dll
mono.js:1 Loaded: MySaaSPlace.Wasm.dll
mono.js:1 Loaded: mscorlib.pdb
mono.js:1 Loaded: System.dll
mono.js:1 Loaded: System.Xml.dll
mono.js:1 Loaded: Uno.UI.pdb
mono.js:1 Loaded: mscorlib.dll
mono.js:1 Loaded: Uno.UI.dll
mono.js:1 initializing mono runtime
mono.js:1 DEBUGGING ENABLED
mono.js:1 >>mono_wasm_runtime_ready
uno-bootstrap.js:324 Done loading the BCL
uno-bootstrap.js:339 Loading dependency (jquery-pep)
uno-bootstrap.js:339 Loading dependency (setImmediate)
uno-bootstrap.js:339 Loading dependency (Uno.UI)
uno-bootstrap.js:339 Loading dependency (jquery-pep)
uno-bootstrap.js:339 Loading dependency (setImmediate)
uno-bootstrap.js:339 Loading dependency (Uno.UI)
uno-bootstrap.js:339 Loading dependency (AppManifest)
uno-bootstrap.js:332 Loaded dependency (Uno.UI)
uno-bootstrap.js:395 Debugging hotkey: Shift+Alt+D (when application has focus)
mono.js:1 >>>mono_wasm_get_loaded_files

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
Thanks for the report! In recent mono builds, the debugger seems to have changed and does not work properly.

In the meantime, you can use those:
```xml
<PackageReference Include="Uno.Wasm.Bootstrap" Version="1.0.0-dev.231" />
<DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.0-dev.231" />
```

**Comment by iosub** [comment]
I get error
he FetchEvent for "http://localhost:54171/" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
The FetchEvent for "http://localhost:54171/" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
The FetchEvent for "http://localhost:54171/" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
The FetchEvent for "http://localhost:54171/" resulted in a network error response: the promise was rejected.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
uno-bootstrap.js:442 Registering service worker now
uno-bootstrap.js:445 Service Worker Registered
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_MONO_RUNTIME_MODE=Interpreter
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_LINKER_ENABLED=True
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_DEBUGGER_ENABLED=True
uno-bootstrap.js:11 Setting UNO_BOOTSTRAP_MONO_RUNTIME_CONFIGURATION=release
mono.js:1 Loaded: MySaaSPlace.Wasm.pdb
mono.js:1 Loaded: Mono.Security.dll
mono.js:1 Loaded: System.Numerics.dll
mono.js:1 Loaded: System.Numerics.pdb
mono.js:1 Loaded: System.Drawing.Common.dll
mono.js:1 Loaded: System.Net.Http.dll
mono.js:1 Loaded: System.Drawing.Common.pdb
mono.js:1 Loaded: System.Net.Http.pdb
mono.js:1 Loaded: System.ServiceModel.Internals.dll
mono.js:1 Loaded: System.ServiceModel.Internals.pdb
mono.js:1 Loaded: Mono.Security.pdb
mono.js:1 Loaded: Uno.Foundation.dll
mono.js:1 Loaded: Uno.Foundation.pdb
mono.js:1 Loaded: Microsoft.Extensions.Logging.Abstractions.dll
mono.js:1 Loaded: Uno.Core.dll
mono.js:1 Loaded: Microsoft.Practices.ServiceLocation.dll
mono.js:1 Loaded: Microsoft.Extensions.Logging.dll
mono.js:1 Loaded: System.Runtime.Serialization.pdb
mono.js:1 Loaded: Uno.pdb
mono.js:1 Loaded: System.ServiceModel.pdb
mono.js:1 Loaded: Uno.UI.Wasm.pdb
mono.js:1 Loaded: WebAssembly.Bindings.dll
mono.js:1 Loaded: System.Core.pdb
mono.js:1 Loaded: Uno.Xaml.dll
mono.js:1 Loaded: System.Collections.Immutable.dll
mono.js:1 Loaded: Uno.dll
mono.js:1 Loaded: System.Core.dll
mono.js:1 Loaded: System.ServiceModel.dll
mono.js:1 Loaded: Uno.UI.Wasm.dll
mono.js:1 Loaded: System.pdb
mono.js:1 Loaded: MySaaSPlace.Wasm.dll
mono.js:1 Loaded: System.Runtime.Serialization.dll
mono.js:1 Loaded: System.Xml.pdb
mono.js:1 Loaded: mscorlib.pdb
mono.js:1 Loaded: System.dll
mono.js:1 Loaded: System.Xml.dll
mono.js:1 Loaded: Uno.UI.pdb
mono.js:1 Loaded: mscorlib.dll
mono.js:1 Loaded: Uno.UI.dll
mono.js:1 initializing mono runtime
mono.js:1 DEBUGGING ENABLED
mono.js:1 >>mono_wasm_runtime_ready
uno-bootstrap.js:23 Uncaught (in promise) TypeError: config.add_bindings is not a function
    at uno-bootstrap.js:23
    at mono.js:1

**Comment by iosub** [comment]
I got the error with 
PackageReference Include="Uno.Wasm.Bootstrap" Version="1.0.0-dev.231" 
DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.0-dev.231" 

because Im using:
https://jenkins.mono-project.com/job/test-mono-mainline-wasm/2486/label=ubuntu-1804-amd64/Azure/processDownloadRequest/2486/ubuntu-1804-amd64/sdks/wasm/mono-wasm-41672cbc74f.zip

They have fix my System.Net.CookieContainer() bug
https://github.com/mono/mono/issues/12871

any solution ???

**Comment by jeromelaban** [comment]
Should be addressed by https://github.com/nventive/Uno.Wasm.Bootstrap/pull/79
