### ISSUE TITLE
DataTriggerBehavior fails to set a property

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#738]
## I'm submitting a...
- Bug report

## Current behavior
The following code does not work :
> ```
> <Image Grid.Column="0" HorizontalAlignment="Center" VerticalAlignment="Center" Stretch="None">
> 	<i:Interaction.Behaviors>
> 		<ic:DataTriggerBehavior Binding="{Binding Discovered}" Value="false">
> 			<ic:ChangePropertyAction PropertyName="Source" Value="/Assets/Images/icon_mount.png"/>
> 		</ic:DataTriggerBehavior>
> 		<ic:DataTriggerBehavior Binding="{Binding Discovered}" Value="true">
> 			<ic:ChangePropertyAction PropertyName="Source" Value="/Assets/Images/icon_mount_available.png"/>
> 		</ic:DataTriggerBehavior>	
> 	</i:Interaction.Behaviors>
> </Image>
> ```

See the full repro: https://github.com/pdecostervgls/Uno-DataTriggerBehaviorImageSourceRepro

## Environment

```
Nuget Package: 1.43.1
Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
This is a limitation of the current `Uno.Microsoft.Xaml.Behaviors.Uwp.Managed` package, which will be updated soon to support this case properly. It was disabled at the time of the build because the `XamlReader` type was not supported by Uno.

As a workaround, instead of:
```xml
<ic:ChangePropertyAction PropertyName="Source" Value="/Assets/Images/icon_mount.png"/>
```
Use :
```xml
<ic:ChangePropertyAction PropertyName="Source"  TargetObject="{Binding ElementName=image}">
    <ic:ChangePropertyAction.Value>
        <BitmapImage UriSource="/Assets/checkbox_unchecked.png"/>
    </ic:ChangePropertyAction.Value>
</ic:ChangePropertyAction>
```

**Comment by pdecostervgls** [comment]
@jeromelaban Thanks for the workaround and fix.
