### ISSUE TITLE
Implement ShowComposeSmsMessageAsync

### ISSUE THREAD

**Issue by MartinZikmund** [nventive/Uno#747]
## I'm submitting a...
- Feature request

## Current behavior
`NotImplementedException`

## Expected behavior
Implement `Windows.ApplicationModel.Chat.ChatMessageManager.ShowComposeSmsMessageAsync` and related APIs so that the following code works:

```
public async Task PrepareSmsAsync( string recipientNumber, string text )
{
    var chatMessage = new Windows.ApplicationModel.Chat.ChatMessage();
    chatMessage.Body = text;
    chatMessage.Recipients.Add( recipientNumber );
    await Windows.ApplicationModel.Chat.ChatMessageManager.ShowComposeSmsMessageAsync( chatMessage );
}
```
## Environment

Nuget Package: Latest

Package Version(s): Latest

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by MartinZikmund** [comment]
I will take care of implementing this.

**Comment by davidjohnoliver** [comment]
You may want to take a look at [Xamarin Essentials](https://github.com/xamarin/Essentials).
