### ISSUE TITLE
VisualStateManager within UserControl doesn't work on iOS and Android

### ISSUE THREAD

**Issue by pdecostervgls** [nventive/Uno#804]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior
When using a UserControl, the VisualStateManager does not go to a defined state.

## Expected behavior
The UserControl would show the changes that are associated with the defined state.

## Minimal reproduction of the problem with instructions
Repro @ https://github.com/pdecostervgls/uno-repro-usercontrolvsm

### UWP
1. Click on Checked 
2. Observe the StateName Textblock changing text and the image changing to checked image.

### Android
1. Click on Checked 
2. Observe the StateName Textblock not changing text and the image not changing to checked image.

## Environment

```
Nuget Package: 

Uno.UI: 1.45.0-dev.1327

Package Version(s): 
Uno.UI: 1.45.0-dev.1327

Affected platform(s):
- [x] iOS
- [x] Android
- [?] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.0.1)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by pdecostervgls** [comment]
Whats the status on this? It's currently my only blocking issue preventing me from releasing to testers.

**Comment by jeromelaban** [comment]
@pdecostervgls I've just tested your sample, and the behavior of both Android and WebAssembly is in line with UWP (both the TextBlock and Image are updated).

I tested with 1.45.0-dev.1397 and 1.45.0-dev.1327.

Could you check again ? Thanks!

**Comment by pdecostervgls** [comment]
@jeromelaban Turned out, it was because the UserControl's constructor doesn't get called if it has no properties. I'll modify the documentation to note this requirement for getting the VSM working.
