### ISSUE TITLE
Several ListView related issues

### ISSUE THREAD

**Issue by queequac** [nventive/Uno#82]
Currently the ListView has several issues.

The `Items` property cannot be used to set items (e.g. directly within XAML). Binding the `ItemsSource` seems to feed in items which can also be seen on the `Items` collection then.

ItemsPanelTemplate seems to be ignored. The list view ignores for example the stackpanel as configured below. (Running on Windows 10 the list view has exactly the 200 pixels height. Under Android it's always just the space required by the items.
```
<ListView.ItemsPanel>
   <ItemsPanelTemplate>
      <ItemsStackPanel Orientation="Vertical" Height="200" />
   </ItemsPanelTemplate>
</ListView.ItemsPanel>
```

In general I did not yet get any of my existing code working at all. I have styled item containers, etc. and my list view does not even get a size. Got only green field projects with simple list views working. :(

Tested on Android.

**Comment by Dissolute** [comment]
Just a note that ItemsStackPanel and ItemsWrapGrid are 'special' panels in Uno, as described [here](https://github.com/nventive/Uno/blob/master/doc/articles/ListViewBase.md#internal-implementation). Their properties are forwarded to the native ListView layouters on each platform; they don't actually exist in the visual tree.

**Comment by Dissolute** [comment]
1. ItemsContainerStyle should be working, but UWP seems to implicitly template-bind the Content to the ContentPresenter, which Uno doesn't do. You need to add 'Content="{TemplateBinding Content}"' like so:
```
<Style TargetType="ListViewItem" x:Key="TestListViewItemStyle">
				<Setter Property="Template">
					<Setter.Value>
						<ControlTemplate TargetType="ListViewItem">
							<ContentPresenter Content="{TemplateBinding Content}" />
						</ControlTemplate>
					</Setter.Value>
				</Setter>
			</Style>
```

2. Deriving from ListView is supported, but you run into a general limitation with derived controls in Uno which is that they don't currently detect the default Style of the base class. As a workaround, you can copy-paste the default ListView style [from here](https://github.com/nventive/Uno/blob/master/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml) and use it as the default Style for your derived class (changing the target types of the Style and the template).

**Comment by queequac** [comment]
@Dissolute That's what my ItemContainerStyle already looks like... there seems (again) to be unexpected  behavior. I reduced my XAML to a minimal sample (listview with item container style having the contentpresenter on red background, data template with just a text box on blue background)
What I discovered: If I set the item container style, the item template is ignored (red background), without container style I get the blue items.

**Comment by Dissolute** [comment]
Yes, I forgot to mention that ContentTemplate (and ContentTemplateSelector) have the same limitations. You actually need the following:
```
<ContentPresenter Content="{TemplateBinding Content}" 
				  ContentTemplate="{TemplateBinding ContentTemplate}"
				  ContentTemplateSelector="{TemplateBinding ContentTemplateSelector}"/>
```

**Comment by queequac** [comment]
Nope, container remains red, still no blue content for my items. :(

**Comment by jeromelaban** [comment]
@queequac could you share a sample of what you're trying to achieve, using the quickstart sample as a base ?

**Comment by queequac** [comment]
@jeromelaban Finally got it working, was some fault in my sample. So ItemContainerStyle seems to work. Sorry for the confusion. :)
