### ISSUE TITLE
Android Border overalaps at corners

### ISSUE THREAD

**Issue by MartinZikmund** [nventive/Uno#840]
## I'm submitting a...
 - Bug report (I searched for similar issues and did not find one) 

## Current behavior
Semi-transparent borders overlap at the corners on Android as they are all rendered across the full width/height of the control.

XAML:

    <StackPanel Spacing="30">
        <Border HorizontalAlignment="Center" Background="Red"  VerticalAlignment="Center" Width="100" Height="100" BorderBrush="#88000000" BorderThickness="10,20,30,40" />
        <Border HorizontalAlignment="Center" Background="Red"  VerticalAlignment="Center" Width="100" Height="100" BorderBrush="#88000000" BorderThickness="10,0,0,40" />
    </StackPanel>

![Screenshot_20190502-213920__01](https://user-images.githubusercontent.com/1075116/57120109-c5b88d00-6d23-11e9-8acc-af97f8fa1c59.jpg)

## Expected behavior

**UWP:**

![Screenshot_20190502-215009](https://user-images.githubusercontent.com/1075116/57120203-91919c00-6d24-11e9-8b95-7b15cb5585c8.jpg)

It is subtle, but as many built-in controls like `TextBox` actually have a semi-transparent border, it is easy to spot.

## Environment

Nuget Package: latest

Package Version(s): latest

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [x] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
Might be a problem on iOS as well, don't have access to a Mac right now, if it is broken too, I will fix it there as well in separate PR.

**Comment by jeromelaban** [comment]
@MartinZikmund did you get a chance to validate on iOS ?

**Comment by MartinZikmund** [comment]
@jeromelaban Yes, I actually fixed it on both platforms with #841 so this can be closed.

**Comment by jeromelaban** [comment]
Thanks!
