### ISSUE TITLE
Cannot assign x:Name value to DataTemplateSelector in xaml resources

### ISSUE THREAD

**Issue by peternary** [nventive/Uno#846]
## I'm submitting a...

- Regression (a behavior that used to work and stopped working in a new release)

## Current behavior

If you try to assign a value to the x:Name attribute of a DataTemplateSelector then Android and WASM fail on build.  Works in UWP.

## Expected behavior

Should build properly on all platforms

## Minimal reproduction of the problem with instructions
Attempt to build the following project:
[App7.zip](https://github.com/nventive/Uno/files/3153845/App7.zip)

## Environment

```
Nuget Package:
Uno.UI
Package Version(s):
1.45.0-dev.1448
Affected platform(s):
- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Fixed by PR #1112
