### ISSUE TITLE
Cannot open connection with Uno.Wasm.WebSockets

### ISSUE THREAD

**Issue by peternary** [nventive/Uno#855]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)

## Current behavior
Calling ConnectAsync on a Uno.Wasm.WebSockets.WasmWebSocket object fails with what appears to be a mono error

## Expected behavior

ConnectAsync should open a connection appropriately

## Minimal reproduction of the problem with instructions
Build and launch the attached app in Wasm and attempt to connect.  Same sample app works in Uwp.
[UnoWebsocketSample.zip](https://github.com/nventive/Uno/files/3167745/UnoWebsocketSample.zip)

## Environment

```
Nuget Package:
Uno.UI
Package Version(s):
1.45.0-dev.1455
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is now fixed by https://github.com/nventive/Uno.Wasm.WebSockets/pull/5.

The mono runtime changed enough for the javascript interop to break, updating to `Uno.Wasm.WebSockets.1.0.0-dev.21` will fix the issue.
