### ISSUE TITLE
Wasm debugger - question

### ISSUE THREAD

**Issue by zbigniew-gajewski** [nventive/Uno#86]
I have found [this message on Twitter](https://twitter.com/jlaban/status/1013641140845842438) which probably means, that mon-Wasm is already prepared for debugging C# source code. 
When (approximately) it will be available in Uno-Wasm?

**Comment by jeromelaban** [comment]
@zbigniew-gajewski iOS/Android debugging is already functional, as in any Xamarin native application.

As for the wasm part, the debugging experience is **very** rough. I would not expect it to be easily useable for at least two or three months... But that's only my guess, only the Mono team knows :smile:

**Comment by jeromelaban** [comment]
For those questions, don't hesitate to come and [chat on gitter](https://gitter.im/uno-platform/Lobby),

**Comment by zbigniew-gajewski** [comment]
Ok, thanks for the answer and for the link to gitter. I hoped, that there is some 'unofficial' way of debugging Uno-Wasm :) but 2-3 months is acceptable.
