### ISSUE TITLE
WASM System.InvalidOperationException: The given header was not found.

### ISSUE THREAD

**Issue by iosub** [nventive/Uno#861]
## I'm submitting a...

 Bug report (I searched for similar issues and did not find one) 

## Current behavior
on the server I have enable cors
 app.UseCors(Microsoft.Owin.Cors.CorsOptions.AllowAll);

WASM does not get all http Headers send by the server
with this code : 

HttpResponseMessage responseMessage = await Client.GetAsync(ApiUrl + "?pagenumber=" + pagina + "&pagesize=" + 5);
                var Pruebaheader = responseMessage.ToString(); 
                Console.WriteLine(Pruebaheader);
                IEnumerable<string> headerValues = responseMessage.Headers.GetValues("Paging-Headers");

I just get
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
 {
   Cache-Control: no-cache
   Pragma: no-cache
   Content-Type: application/json; charset=utf-8
   Expires: -1
 }

on a UWP I get
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Server: Microsoft-IIS/10.0
  Paging-Headers: {"totalCount":169732,"pageSize":5,"currentPage":1,"totalPages":33947,"previousPage":"No","nextPage":"Yes"}
  Cache-Control: no-cache
  X-AspNet-Version: 4.0.30319
  Date: Tue, 14 May 2019 14:27:46 GMT
  X-Powered-By: ASP.NET
  X-SourceFiles: =?UTF-8?B?QzpcTVNQXDIwMThcRGV2XERldlxXZWJBcGlcTmV0QXV0aFxJcmF0aVByb3h5XGFwaVxUX0FSVElDVUxPUw==?=
  Pragma: no-cache
  Content-Length: 6935
  Content-Type: application/json; charset=utf-8
  Expires: -1
}

## Environment

```
Nuget Package:

Package Version(s):
"Uno.Wasm.Bootstrap" Version="1.0.0-dev.269"
"Uno.UI" Version="1.45.0-dev.1434" />
Affected platform(s):
- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Which HttpHandler are you using ? Do you see those headers in the browser's response ?

**Comment by iosub** [comment]
HI
I found a solution it was a CORS issue 
here is the fix
 [EnableCors(origins: "*", headers: "*", methods: "*", exposedHeaders: "X-Paging-Headers")]
    public class T_ARTICULOSController : ApiController
