### ISSUE TITLE
SamplesApp crashes on UWP

### ISSUE THREAD

**Issue by MartinZikmund** [nventive/Uno#972]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)

## Current behavior
Samples app crashes when launched on UWP with the following error - 

```
System.ArgumentException: The parameter is incorrect.
priority
   at Windows.UI.Core.CoreDispatcher.RunAsync(CoreDispatcherPriority priority, DispatchedHandler agileCallback)
   at SamplesApp.App.OnLaunched(LaunchActivatedEventArgs e)
```

## Expected behavior
App should not crash on launch.

## Minimal reproduction of the problem with instructions
I have found out it happens on the following line in `OnLaunched`:

```
var n = Windows.UI.Xaml.Window.Current.Dispatcher.RunAsync(
	CoreDispatcherPriority.Idle,
	() => Console.WriteLine("Done loading " + sw.Elapsed));
```

Not sure why the recent change caused this for me.

## Environment

```
Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Right, my bad. It's not possible to call `RunAsync` with Idle, it's only possible with `RunIdleAsync`.

**Comment by ghuntley** [comment]
I've got this. Sending in fix now.

**Comment by NGame1** [comment]
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Windows.UI.Xaml.Window.Current.get returned null.

```await Windows.UI.Xaml.Window.Current.Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, delegate
            {

            });```

**Comment by NGame1** [comment]
I find a workaround for it. 

            Loaded += MainPage_Loaded;

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            PageViewModel.Dispatcher = Dispatcher;
        }

Name your ViewModel to `PageViewModel` and define 

        public CoreDispatcher Dispatcher { get; set; }

in your ViewModel properties then you can easily call 

            await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async delegate{});

tested on UNO.UI 1.45.0-dev 1817

**Comment by ghuntley** [comment]
Fixed by https://github.com/nventive/Uno/pull/1111
