### ISSUE TITLE
Setting Stretch in MediaPlayerElement causes an exception

### ISSUE THREAD

**Issue by davidjohnoliver** [nventive/Uno#977]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)

## Current behavior

NullReferenceException (MediaPlayer isn't set until OnApplyTemplate() is called)

## Expected behavior

No exception. Stretch should be applied correctly when MediaPlayer is ready.

## Minimal reproduction of the problem with instructions

```xaml
    <MediaPlayerElement Source="http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4"
						Stretch="Fill"
						AreTransportControlsEnabled="True"
						AutoPlay="True" />
```

## Environment

```
Nuget Package:

Package Version(s): 1.45.0-dev.1652

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Resolved by https://github.com/nventive/Uno/pull/979
