### ISSUE TITLE
Uno.Wasm.WebSockets tries to pass invalid value to interop

### ISSUE THREAD

**Issue by peternary** [nventive/Uno#984]
## Current behavior

When receiving data from a websocket WasmWebSockets.js makes a call to WebSocketInterop.dispatchReceivedBinaryMethod passing a non-existent value 'array', which prevents receive from working.

## Expected behavior

WebSocketInterop.dispatchReceivedBinaryMethod should be passed the local variable 'ptr' instead of 'array'.

## How to reproduce it (as minimally and precisely as possible)
[UnoWebsocketSample.zip](https://github.com/nventive/Uno/files/3237650/UnoWebsocketSample.zip)
Build the attached project, connect to the remote server, and attempt to send a string.

## Environment

Nuget Package:
Uno.Wasm.WebSockets
Package Version(s):
v1.0.0-dev.21
Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Thank-you for attaching a repro @peternary.

**Comment by peternary** [comment]
I have tested, and simply replacing 'array' with 'ptr' in the dispatchReceivedBinaryMethod call fixes the issue

**Comment by jeromelaban** [comment]
Indeed, I missed that change for some reason. That will fix it: https://github.com/nventive/Uno.Wasm.WebSockets/pull/6
